DFEAGILEDEVOPS/MTC

pupil/assets/javascripts/speedcheck.js, pupil/bin/extract-logins-and-answers.js, pupil/gulpfile.js, pupil/models/answer.js, pupil/package.json, pupil/server.js, pupil/spec/models/answer.spec.js, pupil/spec/models/feedback.spec.js, pupil/spec/models/logon-event.spec.js
Some lint fixes for the pupil app.  The biggest win is ignoring the vendor javascript which was causing reams of output to appear when running `standard` from the cli.
Current output is now more manageable as it is only a few lines.
=> Pupil lint fixes

dirty-deploy-heroku-admin.sh
This is made problematic because we have a multi-app repository.  The fix is to create a new temp git repo and deploy from there.
=> Add script to deploy admin to heroku

docker-compose.yml, pupil-spa/Dockerfile
The image build is hanging in VSO, likely due to the `nginx -g daemon off;` command in the dockerfile for the SPA.
Moving this command to compose.  Concerned that once deployed to Azure it will simply fire up and exit.  But one step at a time....
=> Docker nginx fixes

pupil-spa/src/app/login.response.mock.json, pupil-spa/src/app/question.service.spec.ts, pupil-spa/src/app/question.service.ts, pupil-spa/src/app/storage.service.spec.ts, pupil-spa/src/app/storage.service.ts
created Union Type called StorageKey which narrows the keys used in the storage service to those which reflect each storage entity (questions, config, session etc...)
refactored question service and spec to accommodate this as tests were failing.
=> strongly type Storage Keys to avoid mismatches

.travis.yml, pupil-spa/karma.conf.js, pupil-spa/package.json, pupil-spa/src/app/user.service.spec.ts
This PR can be considered complete when the travis build executes the unit tests via the `test-single` script added to package.json.
The pupil tests have also been omitted as this is no longer under development and will soon be removed.
=> run ng test during travis build on SPA

pupil-spa/src/app/login-success/login-success.component.spec.ts, pupil-spa/src/app/login-success/login-success.component.ts, pupil-spa/src/app/storage.service.ts, pupil-spa/src/app/user.service.spec.ts, pupil-spa/src/app/user.service.ts
@jon-shipley @GuyHarwood Keep in mind session always comes as undefined as it's not part of the api's response payload.
=> Fix data population errors to redirect to successful login page

pupil-spa/Dockerfile
postinstall called explicitly to ensure govuk assets are copied into intermediary build container
=> npm postinstall script not firing on container image build

pupil-spa/src/app/login/login.component.spec.ts, pupil-spa/src/app/login/login.component.ts, pupil-spa/test/features/login_page.feature
we should only clear storage on logout, currently.
next sprint includes work to time out the session.
=> revert code that cleared storage when loading login component.

pupil-spa/src/app/check/check.component.ts
Present double-tap from zooming in when performing the check on an iPad.  This is likely to occur when entering repeated digits.
Just calling event.preventDefault is not enough as this will also disable the virtual keypad.  Triggering the click event by calling `event.target.dispatchEvent(new Event('click'));` adds normal functionality back in.
=> Disable double-tap zooms on iPad 

pupil-spa/src/app/feedback/feedback.component.spec.ts, pupil-spa/src/app/phase-banner/phase-banner.component.spec.ts
Further unit test coverage for components:
- 'phase-banner'
- 'feedback'
=> Further unit tests

admin/Dockerfile
Azure engineers say using alpine can cause the database connectivity issues we are seeing.
Moving to node-8 to see if it fixes the problem.
=> docker base image change to fix azure connectivity issues

admin/controllers/school.js
Quick fix: resolve an issue where CosmosDB is unable to fetch multiple documents in one go.  
MongoDB API incompatibility.
=> Temp fix for CosmosDB

admin/.dockerignore, admin/.gitignore, admin/app.js, admin/bin/psychometricians-report-v2.js, admin/package.json, admin/yarn.lock
Dotenv adds the convenience of specifying environment variables in a `.env` file, which is not added to source control.  Therefore meaning you do not need to pass args, nor maintain these settings in your shell `rc` files.
I have explicitly added this to the ps report v2 for convenience.
=> Add dotenv package to admin app

admin/data/migrations/migrations/20170611124045-add-known-test-account.js, admin/services/pupil-authentication.service.js
introduction of pin expiry meant that the test user account no longer worked.
=> Fix issue with test account unable to login

pupil-spa/src/app/warmup-complete/warmup-complete.component.spec.ts
This test has been changed as the behaviour was inconsistent
=> Assign spy calls to a variable and detect the audit event based on sequence

admin/services/data-access/check.data.service.js, admin/spec/service/data-access/check.data.service.spec.js, admin/test/features/question_time_limits.feature, admin/test/features/time_between_questions.feature
- Changed findOne to find since chain sort method is throwing an error on dev mongo console
- removing ascending part from sorting which also throws an error
=> Simplify check data service find latest check call

admin/data/migrations/migrations/20180111142806-speech-synth-test-account-flag.js
the speech synthesis enabled test account does not have the `isTestAccount` flag set, so the pin is being wiped every night when the pin purge job runs.
=> set isTestAccount flag for speech synth user

admin/config.js, admin/services/pin-generation.service.js
For dev & test purposes, allow the pin expiry time to be configurable via `process.env.OVERRIDE_PIN_EXPIRY` which is exposed via `config.OverridePinExpiry`
I considered a check for production mode, but we may well want to test in production mode with this enabled.
=> make pin expiry time configurable

admin/data/sql/migrations/054.do.update-admin-passwords.js, admin/data/sql/migrations/054.undo.update-admin-passwords.js
Migration gives an instance of the admin app the opportunity to configure different passwords for the default roles in the admin app.
This will typically be left as-is for dev and test environments.
=> configurable default passwords

admin/app.js
Bugfix: allow Windows 10 with Office installed to upload csv files
=> Add another MS mime-type to the allowed mime-types for upload.

admin/authentication/local-strategy.js
caught this in the log output from UAT and dev.
Fails to save valid logons because nca tools fields are passed in.  they are no longer needed.
=> remove surplus fields

admin/assets/javascripts/global-scripts.js
Re-validate sticky banner when group filters are applied to pupil's list.
=> bug/19059 - Bug fix.

admin/views/contact.ejs, admin/views/partials/_footer_support_links.ejs, admin/views/school/school-home.ejs
School landing page changes - 
- The summary under "Pupils not taking the check" change summary text to "Enter a reason for pupils who are unable to take the check" - change from "were" to "are"
- The summary under the HDF change summary text to "Complete the headteacher's declaration form after you have submitted your pupil register"
Remove Welsh link from footy
Add breadcrumbs to Contact page
Remove help from footer
=> Updates to copy and links 

admin/package.json, admin/yarn.lock
`yarn startd` will execute sql migrations and run the admin app
migrate-mongo introduces a vulnerability via package dependencies, plus we no longer require mongo migrations.
=> bug/19414. add startd script to run migrations then start.  remove migrate-mongo

admin/app.js, admin/config.js
further to the implementation of express logging via winston, this change ensures it is only enabled if explicitly configured, and defaults back to morgan for less verbose dev output.
=> toggle verbose express logging

admin/app.js
* GA required connect-src for google-analytics
* unsafe-inline error fixed, but the underlying cause needs understanding
=> Fix CSP policy for Safari

admin-assets/nginx/default.conf, admin/azure.js
this should stop app insights package from trying to process errors.
also stops it capturing logging from winston.
=> disable insights error handling and logging

admin/services/data-access/completed-check.data.service.js, admin/services/data-access/psychometrician-report-cache.data.service.js
*  `sqlFindUnprocessedChecks` - now only returns at most 250 checks.  This fixes a bug where large reports caused SQL Server to reject the update
* update `completedCheckDataService` - to only find rows that have something in the `data` column
=> Update the Psychometric report

deploy/should-it-build.js
we have been hitting the rate limit of 60 calls a minute.  Adding auth details to the parameter raises that to 5000.
=> add github client and secret to API call to raise rate limits

pupil-spa/src/app/check-complete/check-complete.component.spec.ts, pupil-spa/src/app/check-complete/check-complete.component.ts
Set pending_submission local storage flag to false when check complete instead of wiping local storage
=> Feedback redirect issue

test/admin/Dockerfile, test/pupil/Dockerfile
The test containers require google-chrome-stable and had the apt sources added,
but there was no apt-get update to refresh the source list after it, so there was an
error thrown that 'google-chrome-stable could not be found'.
=> 20241 - Fixed the Chrome errors that occur when building the test containers

admin/spec/service/psychometrician-util.service.spec.js, pupil-spa/src/app/login/login.component.html
In order for mobiles to detect the input as numeric, the input type
has to have type="number" and pattern="\d*" as per HTML5 standards.
=> bug/20218 Updated input type and pattern for pupilPin input

admin/config/feature-toggles.Azure-UAT.json
Product owner has requested that UAT behave as default now that the trials are complete.
Rather than delete the UAT configuration and let it fall back to default behaviours, i have left the file in as an example of how it is done.
=> reset feature toggles on UAT

admin/app.js, admin/services/data-access/sql.pool.service.js
This should not affect MTC, as we use `dateTimeOffset`
omitting the value defaults it to `true`
however, its worthwhile running through a full test to see if anything is raised.
=> sql connection - default to UTC

admin/data/sql/migrate-sql.js
Now throwing the error inside the runMigrations async function, which will
be catched in the outer try, which does process.exit(1)
The process.exitCode previously added should have had a throw afterwards
to stop the process, but it doesn't handle the promises well, so .exit(1) does the job
=> Changed the migration error handling to stop the process immediately

admin/data/sql/migrations/083.do.update-spGenAuditTriggers.sql, admin/data/sql/migrations/083.undo.update-spGenAuditTriggers.sql
spGenAuditTriggers currently only works on first pass, as it is `CREATE` only.
Fix simply implements a `DROP IF EXISTS` first, to counter this issue
=> bug/21253 spGenAuditTriggers - drop before create

admin/data/sql/migrations/093.do.add-bulk-permissions-pupil-table.js, admin/data/sql/migrations/093.undo.add-bulk-permissions-pupil-table.js
Include missing bulk permission migration that was omitted due to a higher migration being merged first
=> Include missing migration

admin/app.js, admin/config.js, admin/helpers/cors-options.js, admin/routes/check-started.js, admin/routes/completed-check.js, admin/routes/pupil-feedback.js, admin/routes/questions.js, test/admin/features/step_definitions/add_multiple_pupil_steps.rb
- Remove global wildcard policy
- Implement 'per endpoint' policies
- Allow multiple whitelist domains via config
=> feature/21581 Implement restrictive CORS policy for endpoints only

pupil-spa/src/assets/shared-styles/styles.scss
Allow scrolling using touch input - IE11 Windows 10 touchscreen
=> Fix regression that prevent scrolling on tablets using touch input

admin/controllers/check-form.js, admin/views/test-developer/download-pupil-check-data.ejs
* Increase ajax timeout to 5 mins
* Increase POST controller timeout to 5 mins
* Tested in docker - 5 min timeout observed
* changes to admin only
NOTE - production observes a 30-second timeout, whereas a 1-minute timeout was observed locally which was the ajax timeout.  This suggests that there is something else in prod that is causing the timeout.
=> 22015 - Increase timeout for pupil data generation to 5 minutes

admin/controllers/check-form.js, admin/views/test-developer/download-pupil-check-data.ejs
Cherry picked the same code from the support branch where it is already running in prod
=> 22019 - Increase timeout for pupil data generation to 5 minutes

pupil-spa/src/app/login-success/login-success.component.spec.ts, pupil-spa/src/app/login-success/login-success.component.ts, test/pupil/features/login_page.feature
Ensure the pupil details (name, dob) are wiped as they are rendered on the login confirmation screen.
=> Bug/22133 Remove pupil localstorage after login

admin/Dockerfile
Added files to be copied before doing a yarn install
Because package.json had a postinstall that does gulp copy
and the files to be copied are not there, it was throwing errors
=> Bug/23637 Admin docker build gulp

pupil-spa/src/app/practice-question/practice-question.component.ts
Fix an issue that was preventing Docker from building the pupil-spa.   The `config` var is referenced inside HTML, so needs to be public.
Let me know your thoughts.
=> Fix `ng build --prod`

admin/app.js
we are loading the logger after we start using the logger, hence why no details appear in logs for feature toggle config.
=> move logging initialisation to before feature toggles are set

pupil-spa/Dockerfile, pupil-spa/README.md, pupil-spa/gen_config.sh
- app insights uses `APPINSIGHTS_INSTRUMENTATIONKEY` in azure, so this will ensure smoother integration when done from the Azure Portal.
- added section to readme for env vars with table listing each one
=> Change env var for AI to official one & add env vars to SPA readme

deploy/storage/create-items.sh
the allowedOrigins parameter was not correctly prefixed with a dollar sign.
=> bug/26617 fix parameter prefix for CORS in queue setup script

vsoBuildServer.md
include details on pre-reqs for running nightly builds that depend on ruby TDS library and headless chrome
=> update build server pre-reqs docs

admin/data/sql/migrations/20181129104632.do.drop-view-pupils-eligible-for-pin-generation.sql, admin/data/sql/migrations/20181129104632.undo.drop-view-pupils-eligible-for-pin-generation.sql, admin/data/sql/migrations/20181129104750.do.recreate-view-pupils-eligible-for-live-pin-generation.sql, admin/data/sql/migrations/20181129104750.undo.recreate-view-pupils-eligible-for-live-pin-generation.sql, admin/data/sql/migrations/20181129110126.do.drop-view-pupils-eligible-for-familiarisation-pin.sql, admin/data/sql/migrations/20181129110126.undo.drop-view-pupils-eligible-for-familiarisation-pin.sql, admin/data/sql/migrations/20181129110139.do.recreate-view-pupils-eligible-for-familiarisation-pin.sql
Fixed missing pupil group id from vewPupilsEligibleForXXXPinGeneration views
- Added migrations to drop and recreate the vewPupilsEligibleForFamiliarisationPinGeneration
view with the addition of the pupil group_id
- Added migrations to drop and recreate the vewPupilsEligibleForLivePinGeneration
view with the addition of the pupil group_id
=> Fixed missing pupil group id

functions/check-expiry/function.json
Runs every 3 minutes when the seconds are at 30 to avoid conflicts.
Works locally:
=> Fix cron expression that fails on Azure

admin/app.js
Node is serving static files.  This commit moves the express app static file handler to *before* the session initialisation, so that session calls are not made when serving static files.
=> Prevent session calls for static files

admin-assets/Dockerfile, admin/Dockerfile, pupil-api/Dockerfile, pupil-spa/Dockerfile
Bump docker base images as far up as feasibly possible.
admin & auth unable to move to node 10 until we have resolved compatibility issues
=> bump docker images to lower vulnerabilities

admin/data/sql/migrations/20190324141230.do.alter-pupil-upsert.sql, admin/data/sql/migrations/20190324141230.undo.alter-pupil-upsert.sql
Remove the DELETE statement from `spPupilCensusImportFromStaging`
```
> diff -w  20190324141230.undo.alter-pupil-upsert.sql  20190324141230.do.alter-pupil-upsert.sql
33,39d32
< 
<   -- Delete all existing pupils not registered to test schools
< DELETE FROM [mtc_admin].[pupil]
< FROM [mtc_admin].[pupil] p
<        INNER JOIN [mtc_admin].[school] s ON (p.school_id = s.id)
< WHERE s.leaCode <> 999;
< 
```
=> Remove delete block when inserting pupils

pupil-spa/src/app/check/check.component.ts
- For pupils with AA next button, this was using the same
timer between sessions. So for the second person it was at 0
=> 31718 - Added timer reset on sign out, so it's ready for next sign in

admin/data/sql/migrations/20190417091050.do.add-reason-required-to-next-button-aa.sql, admin/data/sql/migrations/20190417091050.undo.add-reason-required-to-next-button-aa.sql
- It was added by modifying a migration, meaning it would be missing
in existing schema
=> Added migration to restore "(reason required)" text to next button AA

admin/services/data-access/azure-blob.data.service.js
promisification of azure blob storage service fails if no azure connection string available.
=> default to empty object when no azure connectivity

admin/data/sql/migrations/20190501174958.do.alter-vew-pupils-with-active-familiarisation-pins.sql, admin/data/sql/migrations/20190501174958.undo.alter-vew-pupils-with-active-familiarisation-pins.sql, admin/data/sql/migrations/20190501175006.do.alter-vew-pupils-with-active-live-pins.sql, admin/data/sql/migrations/20190501175006.undo.alter-vew-pupils-with-active-live-pins.sql
Avoid duplicate active pupil pin records appearing by joining only non deleted pupil attendance records
=> Bug/32245 Duplicate records on pin generated list

admin/data/sql/migrations/20190517144520.do.drop-check.data.sql, admin/data/sql/migrations/20190517144520.undo.drop-check.data.sql, admin/data/sql/migrations/20190517144729.do.drop-sessions.sql, admin/data/sql/migrations/20190517144729.undo.drop-sessions.sql, admin/data/sql/migrations/20190517144735.do.drop-pupillogonevent.sql, admin/data/sql/migrations/20190517144735.undo.drop-pupillogonevent.sql, admin/data/sql/migrations/20190517145506.do.drop-pupilstatuscode-trigger.sql, admin/data/sql/migrations/20190517145506.undo.drop-pupilstatuscode-trigger.sql, admin/data/sql/migrations/20190517145510.do.drop-pupilstatuscode-table.sql, admin/data/sql/migrations/20190517145510.undo.drop-pupilstatuscode-table.sql
- pupilStatusCode table
- pupilLogonEvent table
- sessions table
- check.data column
note: pupilLogonEvent is append only so the trigger should not have been there.  This has been omitted from the undo script.
=> drop obsolete tables and columns

pupil-spa/nginx/default.conf
add additional CSP rule to NGINX to allow app insights tracking script
=> bug/33210-fix pupil spa CSP policy for app insights

admin/models/logger.js
Fix for missing space between error UUID and error message.
This has been tested against azure, and will be signed off once travis passes.
=> add space to logger output

pupil-spa/src/app/aa-fonts/aa-fonts.component.html, pupil-spa/src/assets/shared-styles/elements/_aa-variables.scss, pupil-spa/src/assets/shared-styles/elements/_virtual-keyboard.scss, test/pupil-hpa/features/support/page_objects/font_size_page.rb
Reused styles between preview numpad and actual numpad caused numpad button to exceed the preview box's width
Before:
After:
=> Bug/33928 Provided dedicated styling for numpad preview box

admin/services/check-start.service.js, admin/services/data-access/check-form-allocation.data.service.js, admin/services/queue-name-service.js, admin/spec/back-end/service/check-start.service.spec.js, admin/yarn.lock, pupil-api/readme.md, pupil-spa/gen_config.sh, pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts, pupil-spa/src/app/services/check-complete/check-complete.service.ts, pupil-spa/src/app/services/config/config.service.ts
=> Feature/36262 add school UUID to check submission

admin/services/check-form-v2.service.js, admin/services/check-form.service.js, admin/services/check-start.service/check-start.service.js, admin/services/check-start.service/check-start.service.spec.js, admin/services/data-access/redis-cache.service.js, admin/services/redis-key.service.js, admin/spec/back-end/service/check-form-v2.service.spec.js, admin/spec/back-end/service/check-form.service.spec.js
Allocated Check forms are static during a check window and are only modified in exceptional circumstances.   They are fetched from the database every time a teacher generates one or more pins.
- Cache the check forms for 1 month after first fetch.  
- Drop cache when check window form assignments are modified.
- remove obsolete check form modification code from old check form service
=> spike/39361 - cache check forms after first fetch during pin generation

admin/controllers/pupil-pin.js, admin/data/sql/migrations/20200318120158.do.update-check-add-created-by-user-id.sql, admin/data/sql/migrations/20200318120158.undo.update-check-add-created-by-user-id.sql, admin/data/sql/migrations/20200318133108.do.drop-spcreatechecks.sql, admin/data/sql/migrations/20200318133108.undo.drop-spcreatechecks.sql, admin/data/sql/migrations/20200318133218.do.drop-check-table-type.sql, admin/data/sql/migrations/20200318133218.undo.drop-check-table-type.sql, admin/data/sql/migrations/20200318134251.do.recreate-check-table-type-with-user-id.sql, admin/data/sql/migrations/20200318134251.undo.recreate-check-table-type-with-user-id.sql, admin/data/sql/migrations/20200318134838.do.recreate-spcreatechecks-with-user-id.sql, admin/data/sql/migrations/20200318134838.undo.recreate-spcreatechecks-with-user-id.sql, admin/services/check-start.service/check-start.service.js, admin/services/check-start.service/check-start.service.spec.js, admin/services/data-access/pin-generation.data.service.js, admin/views/privacy.ejs
In order to add the new column `createdby_userId` and populate it as part of the check creation process the type needs to be dropped and the `spCreateChecks` procedure recreated.
=> Add createdby_userId during check creation

test/admin-hpa/Gemfile, test/admin-hpa/Gemfile.lock, test/pupil-hpa/Gemfile, test/pupil-hpa/Gemfile.lock
The browserstack-fast-selenium gem has a dependancy on the curb gem. We do not use browserstack-fast-selenium, it was left in and not removed after testing
=> removing unused gem

tslib/src/functions/util-diag/index.ts
the app insights wrapper is causing the function to fail in azure, and takes over 30 seconds for first request to complete locally.
the wrapper was added as a proof of concept to the utility function, and can safely be removed.
=> bug/45188 remove app insights wrapper from util-diag function

deploy/app-insights/CreateReleaseAnnotation.ps1
improve script so we have build number and release name as distinct properties in app insights annotations
=> feature/45307 update data annotation script to include build number and release number/name

admin-assets/nginx/default.conf, pupil-spa/nginx/default.conf
nginx config files were still setting header to active, this should now be disabled.
=> bug/45311 disable xss protection for admin and pupil-spa

admin-assets/nginx/example.conf, api_tests/spec/security_spec.rb, func-consumption/host.json, func-throttled/host.json, pupil-spa/nginx/example.conf
Fix outstanding tests so that they correctly assert for `0` which disables the browser xss prevention check.
=> bug/45543 - verify API headers tests fix

admin/services/data-access/service-bus-queue-metadata.service.js
data service was using wrong property `totalMessageCount` instead of `activeMessageCount`
=> bug/46827 - tech support service bus queue shows total count instead of active

db/migrations/schema-objects/20210707115242.do.alter-mtc-results-checkresult-mark.sql, db/migrations/schema-objects/20210707115242.undo.alter-mtc-results-checkresult-mark.sql
=> 47429 - [db] mask checkResult.mark with a better default

deploy/service-bus/deploy.config.js
- allow size configuration for production environments
- set default TTL to 23 hours
=> feature/47102 - update check-completion queue config

pupil-spa/nginx/default.conf
try_files directive was causing a 404 at the NGINX level, instead of passing it through to the hosted app
=> bug/58316 - NGINX try_files config issue on /sign-in

deploy/service-bus/deploy.config.js
- messages to have max delivery count of 1
- message lifetime reduced to 6 hours
=> bug/59306 ps-report-exec queue configuration updates

admin/availability/middleware.js, admin/routes/pupils-not-taking-the-check.js, admin/views/pupils-not-taking-the-check/select-pupils.ejs, test/admin-hpa/features/pupil_not_taking_check.feature, test/admin-hpa/features/step_definitions/landing_page_steps.rb, test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb, test/admin-hpa/features/support/page_objects/pupil_register_page.rb, test/admin-hpa/features/support/page_objects/pupils_not_taking_check_page.rb
bug in view logic was allowing removal of attendance codes after HDF signed
- fix view logic
- implement guard at routing level
=> bug/59439 prevent attendance changes after HDF signed

test/pupil-hpa/features/a_ps_report.feature, test/pupil-hpa/features/step_definitions/ps_report_steps.rb, tslib/src/functions-ps-report/ps-report-3-transformer/report-line.class.spec.ts, tslib/src/functions-ps-report/ps-report-3-transformer/report-line.class.ts
- set AttemptId, FormID and TestDate to null if the pupil never logged into the check
- if an attendance code is present, do not initialise any of the check data fields
=> bug/59558 PS Report: set attemptId to null if never logged in

deploy/service-bus/deploy.config.js
Increase TTL on the ps-report-export queue to align with functionTimeout and maxAutoRenewDuration
=> Increase ttl on ps-report-export queue

admin/app.js, admin/package.json, admin/services/data-access/sync-results-resync.data.service.js
Axios requests fail with a refused connection.
Forcing IPV4 fixes the issue.
Configured at global level to ensure parity across solution.
=> Bug/65517 axios requests failing to talk to azure functions API

db/migrations/schema-objects/20210129090329.do.create-ps-report-table.sql, db/migrations/schema-objects/20240103120853.undo.rename-table-psychometricreport.sql, tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/csv-transform.spec.ts, tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/csv-transformer.ts, tslib/src/functions-ps-report/ps-report-4-writer/ps-report-writer.service.ts, z_spikes/ps-report-sql-tactical/ps-report-2019.sql
Reverted - SQL changes shouldn't be added to existing migration scripts
https://github.com/DFEAGILEDEVOPS/MTC/pull/3019
=> Reverting changes done as part of 66709 - see PR 3019
