- admin/package.json
- pupil/package.json
Add code coverage reporting using `nyc` from `istanbul`
See: https://github.com/istanbuljs
> add code coverage reporting

- admin/assets/stylesheets/elements/_sign-out.scss
- admin/test/features/step_definitions/phase_banner_steps.rb
- admin/views/partials/_content.ejs
- admin/views/school/_pupil-form.ejs
- admin/views/school/declaration-form.ejs
- admin/views/school/manage-pupils.ejs
- admin/views/school/no-results.ejs
- admin/views/school/school-home.ejs
- admin/views/school/submit-attendance-register.ejs
- admin/views/sign-in.ejs
- admin/views/test-developer/manage-check-forms.ejs
- admin/views/test-developer/view-form.ejs
Some of the tools used: 
1) Chrome extension WAVE
2) Chrome extension Validity
3) Chrome extension 'Siteimprove' 
4) Mac Voice Over tool
5) ZoomText
Guidelines:
https://www.w3.org/WAI/intro/wcag
http://webaim.org/techniques/screenreader/#differences
Please note: Some of the tools are more strict than others, what a check tool may report as "redundant role" may come up as a recommendation or even an error on a different tool.
> Accessibility markup.

- admin/controllers/pupil.js
- admin/controllers/school.js
- admin/services/pupilService.js
- admin/spec/mocks/answers.js
- admin/spec/service/pupilService.spec.js
- admin/views/school/submit-attendance-register.ejs
Implementation + tests.
_As it was taking too long at this stage to do integration tests between mongodb and the app I added **TODOs** to keep them as technical debt for future sprints_
> Fetch score details service call

- admin/assets/stylesheets/elements/_printing.scss
- admin/views/partials/_content.ejs
- admin/views/school/pupils-print.ejs
CSS page break inside is very inconsistent and does generate issues (_extra page at the end_) when used in a table element.
Only solution I could came up with is use multiple tables.
> 12698  Fix page breaks by adding multiple tables

- admin/test/features/step_definitions/add_pupil_steps.rb
- admin/test/features/step_definitions/edit_pupil_steps.rb
- admin/test/features/step_definitions/manage_check_forms_steps.rb
- admin/test/features/support/helpers.rb
- pupil/test/Rakefile
- pupil/test/features/step_definitions/prototype_steps.rb
- pupil/test/features/support/helpers.rb
- pupil/test/features/support/page_objects/check_page.rb
Added Dynamic waiting in some places and also solved exit code issues when the rerun passes but the exit code is still 1
> Rerun exit code and timings

- admin/app.js
- admin/newrelic.js
- pupil/app.js
- pupil/newrelic.js
Only require newrelic when NODE_ENV is 'production'
> Only require newrelic when NODE_ENV is 'production'

- pupil/test/config/browserstack.yml
- pupil/test/features/prototype.feature
- pupil/test/features/step_definitions/prototype_steps.rb
- pupil/test/features/support/hooks.rb
- pupil/test/features/support/page_objects/check_page.rb
- pupil/test/features/warm_up_questions.feature
Windows 7 Chrome 58
54 scenarios (7 skipped, 47 passed)
138 steps (19 skipped, 119 passed)
4m1.990s
> Windows 7 Chrome58 Browserstack

- tslint.json
Experimental - attempt to teach codacy that we are using single quotes in the typescript
> Experimental - attempt to teach codacy 

- pupil-spa/src/app/app.module.ts
- pupil-spa/src/app/check-complete/check-complete.component.html
- pupil-spa/src/app/check-complete/check-complete.component.spec.ts
- pupil-spa/src/app/check-complete/check-complete.component.ts
Add new component CheckComplete to display the /check/complete page.
> Add new check complete component - static page

- test/conf.js
- test/features/pupil-spa/header_footer.feature
- test/features/step_definitions/pupil-spa/headerFooterSteps.js
- test/features/step_definitions/pupil-spa/welcomePage.js
- test/page_objects/pupil-spa/spaSignInPage.js
47 scenarios (47 passed)
125 steps (125 passed)
1m21.652s
> header, feedback and footer tests

- pupil-spa/src/app/audit.service.spec.ts
- pupil-spa/src/app/storage.service.mock.ts
- pupil-spa/src/app/storage.service.spec.ts
auditService - mock storageService
storageService - assert key contents, not order
> Refactor auditService and storageService tests

- pupil-spa/gulpfile.js
- pupil-spa/package.json
- pupil-spa/src/app/user.service.ts
- pupil-spa/src/environments/environment.prod.ts
- pupil-spa/src/environments/environment.ts
Load api url variable from environment and include gulp replace task for build process
> Base api url environment variable per config and gulp task

- pupil-spa/src/app/login/login.component.html
- pupil-spa/src/assets/shared-styles/styles.scss
- pupil-spa/src/public/styles/styles.css
For good measure this also turns off spellcheck (standard HTML5) and autocorrect (non standard attribute for Safari)
> Turn off auto-capitalize for Safari iOS

- admin/spec/routes/questions.spec.js
Unit test fix to reflect latest controller code
> Fix admin unit tests - call chain has now changed

- pupil-spa/src/app/app.module.ts
- pupil-spa/src/app/check/check.component.spec.ts
- pupil-spa/src/app/check/check.component.ts
- pupil-spa/src/app/question.model.ts
- pupil-spa/src/app/question.service.ts
- pupil-spa/src/app/question/question.component.spec.ts
- pupil-spa/src/app/question/question.component.ts
- pupil-spa/src/app/registerInput.service.spec.ts
- pupil-spa/src/app/registerInput.service.ts
- pupil-spa/src/app/user.service.ts
- Recording events from keyboard mouse and virtualkeyboard including touch events
- Introduced tests
> Integrate register input service

- admin/test/features/support/upn_generator.rb
This pr will allow you to generate upn with ease.
To do so please do the following, either be in the admin directory and run  
> ruby -r "./test/features/support/upn_generator.rb" -e "UpnGenerator.generate"
or if using oh my zsh  (https://github.com/robbyrussell/oh-my-zsh) 
setup up a the following: 
> alias upn='ruby -r "/PATH/Projects/MTC/admin/./test/features/support/upn_generator.rb" -e "UpnGenerator.generate"'
Restart your terminal and you can call the upn alias from anywhere:
> ➜  ~ upn
"W826000200002"
> print out upn number for use when testing locally

- admin/assets/stylesheets/elements/_check-windows.scss
Based on UX feedback, this branch fixes the alignment of form buttons on mobile views.
> Form buttons fix for mobile.

- admin/app.js
- admin/azure.js
- admin/package.json
- admin/yarn.lock
Provides rich telemetry in Azure when configured via environment variable.
for more info see here - https://docs.microsoft.com/en-us/azure/application-insights/app-insights-overview
> Feature/16000 - integrate azure application insights

- admin/test/features/pupil_not_taking_check.feature
- admin/test/features/step_definitions/pupil_not_taking_check.rb
- admin/test/features/support/page_objects/pupils_not_taking_check_page.rb
> Scenario for Pupil not taking a check toggle area

- api_tests/helpers/request_helper.rb
- api_tests/spec/security_spec.rb
- api_tests/spec/spec_helper.rb
To run the security admin tests - BASE_URL=AZURE_ADMIN_URL rspec -t @azure_admin
To run the security spa tests - BASE_URL=AZURE_SPA_URL rspec -t @azure_spa
> Change Security test tags so app tests can be run separately 

- admin/controllers/school.js
Restructure the `find` to use `$in` and cast the `ids` to `ObjectId`
> Real fix for generate pins multiple fetch

- pupil-spa/Dockerfile
- pupil-spa/yarn.lock
* Create css files during the build
* Fix an issue with @angular/cli where two versions of webpack were installed.  Fix was to uninstall then reinstall @angular/cli
* Remove out of date postinstall task
> SPA - update docker build

- pupil-spa/Dockerfile
- pupil-spa/src/app/question/question.component.html
Blind fix for failing build on azure
> Fix failing docker build

- admin/services/generate-pins.service.js
- admin/services/pupil-authentication.service.js
- admin/spec/service/generate-pins.service.spec.js
- admin/spec/service/pupil-authentication.service.spec.js
- admin/test/features/step_definitions/create_window_steps.rb
- admin/test/features/step_definitions/edit_check_window_steps.rb
Validate pin for authentication and compare pinExpiresAt value with current date time
> feature/17000 Bug fixes

- admin/controllers/school.js
- admin/services/data-access/pupil.data.service.js
- admin/services/data-access/school.data.service.js
- admin/spec/controllers/school.spec.js
- admin/spec/service/data-access/pupil.data.service.spec.js
- admin/spec/service/data-access/school.data.service.spec.js
Revert find methods to return lean PoJos and replaced save with update methods
> Feature/16348 Update pupil and school documents instead of save

- admin/.gitignore
- admin/services/generate-pins.service.js
- admin/services/pupil.service.js
- admin/spec/service/generate-pins.service.spec.js
- admin/spec/service/pupil.service.spec.js
- admin/test/features/step_definitions/generate_pupil_pins_steps.rb
- admin/views/school/generate-pins-list.ejs
- admin/views/school/generated-pins-list.ejs
* If pupil has same first name and surname, then date of birth is also displayed 
* If pupil has same first name, surname name and same date of birth, then middle name is also displayed
> bug/16347 Display DoB for duplicate names in generated pins page

- admin/lib/validator/pupil-validator.js
- admin/spec/lib/validator/pupil-validator.spec.js
- admin/test/features/edit_pupil.feature
- admin/test/features/step_definitions/add_pupil_steps.rb
- admin/test/features/step_definitions/edit_pupil_steps.rb
- admin/test/features/step_definitions/generate_pupil_pins_steps.rb
UPN validation should only trigger when id is different under the same UPN
> bug/17325 Unique upn validation fix

- admin/controllers/questions.js
- admin/data/migrations/migrations/20171110030904-toggle-speech-synth-on-for-demo-user.js
- admin/models/pupil.js
- admin/services/config.service.js
- admin/services/data-access/pupil.data.service.js
- admin/services/data-access/setting.data.service.js
- admin/spec/lib/validator/check-window-validator.spec.js
- admin/spec/mocks/pupil.js
- admin/spec/mocks/setting.js
- admin/spec/service/config.service.spec.js
- admin/spec/service/data-access/setting.data.service.spec.js
- admin/yarn.lock
- design/schemas/api/CheckSession.json
- pupil-spa/src/app/services/speech/speech.service.spec.ts
- pupil-spa/test/features/login_page.feature
- pupil-spa/test/features/step_definitions/login_page_steps.rb
- pupil-spa/tslint.json
Pass the speech synthesis config to the SPA
> Pass speech synth config to SPA

- admin/controllers/test-developer.js
- admin/views/partials/_breadcrumbs.ejs
- admin/views/test-developer/test-developer-home.ejs
Test developer's role landing page needs only a 'Home' link.
> 17330- Removing unnecessary breadrumb item

- admin/controllers/service-manager.js
- admin/services/date.service.js
- admin/spec/service/date.service.spec.js
Plus a path fix for check windows.
> bug/Unit text fix for method formatDateFromRequest (date service)

- deploy/jobs/purge-pins.js
The scheduled job that purges pins at 4pm daily was not excluding the test accounts.
> Bug in pin purge - exclude test accounts

- admin/services/check-start.service.js
- admin/services/data-access/check.data.service.js
- admin/spec/service/check-start.service.spec.js
- admin/spec/service/data-access/check.data.service.spec.js
- admin/test/features/step_definitions/edit_check_window_steps.rb
Small refactor: move db access to the data-layer
> Refactor check-start-service

- admin/test/features/step_definitions/create_window_steps.rb
Fixed so we have a better way of controlling dates instead
> Refactored so we stop having date issues which cause failures

- api_tests/spec/security_spec.rb
Update the tests as they are failing on the build server
> fix security tests

- admin/controllers/check-form.js
Fix small bug when the remove link doesn't display in the check form page.
> bug/17604 - Bug fix. Remove link not displaying in check form page.

- admin/controllers/pupil.js
- admin/models/pupil.js
- admin/services/data-access/check-window.data.service.js
- admin/services/data-access/pupil.data.service.js
- admin/spec/controllers/pupil.spec.js
- admin/spec/models/pupil.spec.js
- admin/spec/service/data-access/pupil.data.service.spec.js
- admin/yarn.lock
Remove Pupil and School dependencies on mongoose models from pupil controller.
Before:
After:
> Remove controller dependency on Pupil mongoose model

- admin/assets/stylesheets/elements/_restarts.scss
- admin/controllers/restart.js
- admin/services/restart.service.js
- admin/spec/controllers/restart.spec.js
- admin/test/features/restarts.feature
- admin/test/features/step_definitions/restarts_steps.rb
- admin/views/restart/restart-overview.ejs
- admin/views/restart/select-restart-list.ejs
> UI improvements/fixes on the restart list selection

- admin/services/restart.service.js
- Restart status comes back as undefined when using ramda expression on dev environment.
> Replace ramda find expression with array find

- admin/controllers/service-manager.js
- admin/data/sql/migrations/015.do.sample-admin-users.sql
- admin/data/sql/migrations/015.undo.sample-admin-users.sql
- admin/services/data-access/setting.data.service.js
- admin/spec/service/data-access/setting.data.service.spec.js
final changes to complete work on setting.data.service
performs update to SQL server settings table.
all references to `createOrUpdate` modified
> Feature/18301 settings data service refactor (part 2: update query)

- admin/controllers/check-form.js
- admin/controllers/service-manager.js
- admin/services/check-form.service.js
- admin/services/check-window.service.js
- admin/services/data-access/check-form.data.service.js
- admin/services/data-access/check-window.data.service.js
Fixes bugs...
- 18648
- 18652
- 18654
- 18655
- 18656
> Bug fixes for check windows and check forms 

- admin/controllers/contact.js
- admin/routes/index.js
- admin/spec/controllers/contact.spec.js
- admin/test/features/contact.feature
- admin/test/features/sign_in.feature
- admin/test/features/step_definitions/contact_steps.rb
- admin/test/features/step_definitions/sign_in_steps.rb
- admin/test/features/support/page_objects/contact_page.rb
- admin/test/features/support/page_objects/sign_in_page.rb
- admin/views/contact.ejs
- admin/views/partials/_footer_support_links.ejs
In the footer, the link to 'contact' us has been updated to point to a simple page with contact details.
> 18589 - Contact page

- admin/views/contact.ejs
change home to Home in related section on Contact page
> change case of word

- admin/assets/stylesheets/application.scss
- admin/views/school/school-home.ejs
HDF link greyed out and disabled until we re-implement
> disable HDF link

- admin/controllers/pupil-feedback.js
object was incorrectly assigning check_id to id, which failed on SQL insert
> fix check_id insert

- admin/services/data-access/pupil.data.service.js
- This is to fix the sorting issue on select pupils for not taking the check screen.
> Differentiate query sorting based on sort field

- admin/controllers/school.js
Remove the word pupil from confirmation message
> remove the word pupil

- admin/views/school/school-home.ejs
Greys out the school homepage links to these modules
> disable links to HDF, access arrangements and results

- admin/assets/stylesheets/application.scss
- admin/controllers/school.js
- admin/services/data-access/pupil.data.service.js
- admin/services/group.service.js
- admin/spec/controllers/school.spec.js
- admin/spec/mocks/groups.js
- admin/spec/service/group.service.spec.js
- deploy/jobs/purge-pins.sh
Populate groups column in pupil's list.
> feature/18868 - Groups for pupil register

- admin/controllers/questions.js
patch to allow test accounts to login.
This will be extracted to a service with configuration that denies test accounts unless explicitly configured as such.  Tech Debt card created for that work
> allow test accounts to login

- admin/controllers/pupil-pin.js
Handle multiple types of incoming form data
> Fix generate pins

- admin/assets/stylesheets/application.scss
- admin/assets/stylesheets/elements/_not-taking-check.scss
- admin/views/restart/select-restart-list.ejs
- admin/views/school/_pupil-form.ejs
- admin/views/school/select-pupils-not-taking-check.ejs
Hide / show fixed to work correctly on IE. Tested on various IE and Windows versions as well as other browsers via Browserstack.
> bug/17386 - Hide show fix for IE.

- admin/controllers/questions.js
move test account check to before check window check
> allow test user login

- admin/README.md
- admin/app.js
- admin/config.js
- admin/package.json
- admin/services/check-complete.service.js
- admin/yarn.lock
Allow config to disable the automatic marking
Testing:
`AUTO_MARK=false yarn start` to override
> Add config to allow the auto-marking to be disabled

- .travis.yml
- admin/config.js
- admin/data/sql/migrate-sql.js
- admin/test.sh
- admin/test2.sh
- admin/test3.sh
- docker-compose.yml
See if this prevents the segfaults when running on travis
> Drop back to a hopefully more stable version of MSSQL

- admin/services/data-access/group.data.service.js
- admin/test/features/question_time_limits.feature
- admin/test/features/step_definitions/question_time_limit_steps.rb
- admin/test/features/support/page_objects/check_settings_page.rb
- admin/test/features/time_between_questions.feature
- admin/views/service-manager/check-settings.ejs
Cancel link fixed. Tiny fix.
NOTE: Awaiting BAs to confirm if this fix is needed for the feb-trial branch too.
> bug/19323 - Cancel button fix [master]

- admin/services/pin-generation.service.js
- pupil-spa/src/app/instructions/instructions.component.html
- pupil-spa/src/app/login-success/login-success.component.html
- pupil-spa/test/Gemfile.lock
- pupil-spa/test/features/instructions_page.feature
- pupil-spa/test/features/support/page_objects/confirmation_page.rb
- pupil-spa/test/features/support/page_objects/start_page.rb
Copy changes requested for the March trials
> Update copy for the March trials (and March training)

- admin/controllers/pupil-pin.js
- admin/controllers/service-manager.js
- admin/spec/controllers/pupil-pin.spec.js
- admin/views/pupil-pin/pin-print.ejs
BAs requested a change in the date format.
> feature/19771 - Date format on PIN print card 

- admin/assets/stylesheets/elements/_filters.scss
- admin/services/data-access/group.data.service.js
Small PR to sort groups by name in the group filter box.
> bug/19334 - Sorting group by group name

- admin/controllers/questions.js
- admin/services/check-window.service.js
- admin/services/jwt.service.js
- admin/spec/controllers/questions.spec.js
- admin/spec/service/check-window.service.spec.js
- admin/spec/service/jwt.service.spec.js
- pupil-spa/test/features/step_definitions/check_steps.rb
- pupil-spa/test/features/step_definitions/complete_page_steps.rb
- pupil-spa/test/features/step_definitions/pin_expiry_steps.rb
- pupil-spa/test/features/step_definitions/state_steps.rb
Provide epoch time representation of check window's end date time as jwt expiration.
> Extend access token expiration based on check window end date time

- admin/assets/stylesheets/elements/_not-taking-check.scss
- admin/views/restart/restart-overview.ejs
- Increase font size on restart pupils remove link 
- Apply underline on remove link of pupils not taking the check list
> 19326 Remove link ux changes

- admin/assets/stylesheets/application.scss
- admin/views/pupil-register/pupils-list.ejs
- admin/views/restart/restart-overview.ejs
- admin/views/school/school-home.ejs
copy changes
modify sidebar links
remove underline from disabled links
> 20409 copy, sidebar and disabled link changes

- api_tests/spec/security_spec.rb
> 20616 - fix failing security test

- admin/data/sql/migrations/091.do.extend-development-check-window.sql
- admin/data/sql/migrations/091.undo.extend-development-check-window.sql
- admin/spec/service/check-form.service.spec.js
- test/admin/features/step_definitions/add_multiple_pupil_steps.rb
DB update to extend the check window
> [21417] Extend the development  phase check window

- admin/services/role.service.js
> 21941 - Add mapping for ncaUserRole `SchoolNomAA` to map to `TEACHER` role 

- admin/controllers/check-form.js
- admin/spec/controllers/check-form.spec.js
- admin/views/test-developer/upload-and-view-forms.ejs
- admin/views/test-developer/view-check-form.ejs
> Bug/18783 Display form name

- admin/config.js
- admin/controllers/check-form.js
- admin/helpers/logger.js
- admin/services/check-processing.service.js
- treat JS errors as exceptions (why not default to true?!?!?!).
- Introduce explicit log level setting, defaults to debug
> set flag to treat errors as exceptions

- .travis.yml
- admin/app.js
- admin/services/anomaly-report.service.js
- admin/services/psychometrician-util.service.js
- admin/spec/service/psychometrician-report.service.spec.js
- admin/spec/service/psychometrician-util.service.spec.js
- test/admin/features/step_definitions/manage_check_forms_steps.rb
- test/admin/features/support/page_objects/assign_form_to_window_page.rb
Fix error caused by unusual input:  `Cannot read property 'eventType' of undefined`
> 22088 - Trial Hotfix- pupil data generation fails with error

- admin/assets/stylesheets/elements/_filters.scss
- admin/views/pupil-pin/generate-pins-list.ejs
Updated the search bar to be longer as in the prototype
> Task/23265 Elongate filter bar pin generate

- admin/assets/javascripts/pupil-filter-name.js
- admin/views/pupil-pin/generate-pins-list.ejs
Added a workaround for IE/Edge to detect name filter clear events
> Bug/23264 Fix filterbar deletion in Edge

- admin/views/pupil-pin/generate-pins-overview.ejs
- admin/yarn.lock
- test/admin/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
- test/admin/features/support/page_objects/generate_pins_overview_page.rb
> 23266 update description for generate pins

- admin/data/sql/migrations/118.do.move-pupil-pins-to-check.sql
- admin/data/sql/migrations/118.undo.move-pupil-pins-to-check.sql
Edit migration 118
Now takes into account existing data.  Tested on a local DB dump of the dev environment.
> Fix migrations

- admin/services/check-start.service.js
- admin/spec/back-end/mocks/check-form-allocation-familiarisation.js
- admin/spec/back-end/service/check-start.service.spec.js
- functions/yarn.lock
- pupil-api/yarn.lock
- pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
- pupil-spa/src/app/services/check-complete/check-complete.service.ts
- Prevent check submission on pupil spa when practice toggle (config) is enabled
- Prevent check complete sas token generation if the batch of checks generated are non-live (familiarisation)
> Feature/24376 Prevent submission in practice mode

- pupil-spa/src/app/login-success/login-success.component.html
- pupil-spa/src/app/services/speech/speech.service.ts
- 'Do not press next if this is not you' replaced <div> with <p>
> Fixed un-spoken sentence on confirmation page

- admin/data/sql/migrations/153.do.fix-spCreateChecks.sql
- admin/data/sql/migrations/153.undo.fix-spCreateChecks.sql
correction to the subquery that produces an unused pin for a particular school
> fix spCreateChecks subquery

- admin/config/feature-toggles.Azure-DEV.json
- admin/config/feature-toggles.hpa-dev.json
PO requires access arrangements enabled in dev for demo today.
Admin side works without issue, so enabling feature toggle for dev env only.
> enable access arrangements in dev and for hpa mode

- pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
- pupil-spa/src/app/services/check-complete/check-complete.service.ts
- pupil-spa/src/app/submission-pending/submission-pending.component.spec.ts
> Bug/26288 fix SPA app counter on check submission

- admin/package.json
- admin/yarn.lock
admin app failing to start under pm2 due to transports error.
> HOTFIX: rollback to winston v2

- admin/data/sql/migrate-sql.js
Removed unnecessary try/catch and ensured a non 0 exit code is returned on error
> Bug/27484 Migrations exit code

- admin/data/sql/migrations/20181220193807.do.drop-session-trigger.sql
- admin/data/sql/migrations/20181220193807.undo.drop-session-trigger.sql
- admin/data/sql/migrations/20181220194954.do.drop-logonevent-trigger.sql
- admin/data/sql/migrations/20181220194954.undo.drop-logonevent-trigger.sql
- admin/data/sql/migrations/20181220195613.do.alter-sp-gen-audit-triggers.sql
- admin/data/sql/migrations/20181220195613.undo.alter-sp-gen-audit-triggers.sql
Auditing
Prevent the audit triggers from  running on the session and pupilLoginEvent tables
> Bug/27798 disable auditlog trigger on sessions  adminlogonevent tables

- admin/Dockerfile
- admin/config.js
- pupil-api/Dockerfile
> freeze lockfiles and add app insight default config settings

- admin/services/role.service.js
urgent change required for NCA Tools
> add new helpdesk role mapping

- admin/spec/front-end/check-forms.spec.js
- admin/views/check-form/upload-new-forms.ejs
Cancel button broken  on upload new forms page
> fix cancel href

- test/admin-hpa/features/step_definitions/upload_view_forms_v2_steps.rb
- test/admin-hpa/features/support/page_objects/download_pupil_check_data_page.rb
- test/admin-hpa/features/upload_pupil_census.feature
Fixed copy change failures in the nightly build
> Feature/29001 - Fix nightly build copy changes

- admin/views/cookies.ejs
- admin/views/privacy.ejs
- pupil-spa/src/app/loading/loading.component.ts
New cookies added
Updated page timestamp
Some text modifications
> Update cookie page

- admin/data/sql/README.md
- admin/data/sql/seeds/20190207112809.custom.fix-estab-code.sql
- rabbit_enabled_plugins
the recent school dataset seed set incorrect estab codes.
These are corrected in this seed by extracting the estab from the dfeNumber
> fix estab codes by extracting from dfeNumber

- admin/assets/javascripts/pupil-access-arrangements-selection.js
- admin/controllers/access-arrangements.js
- admin/data/sql/migrations/107.do.insert-access-arrangements.sql
- admin/data/sql/migrations/20190213124312.do.aa-next-button-information.sql
- admin/data/sql/migrations/20190213124312.undo.aa-next-button-information.sql
- admin/lib/errors/access-arrangements.js
- admin/lib/validator/access-arrangements-validator.js
- admin/services/access-arrangements.service.js
- admin/services/data-access/pupil-access-arrangements.data.service.js
- admin/services/pupil-access-arrangements.service.js
- admin/spec/back-end/lib/validator/access-arrangements-validator.spec.js
- admin/spec/back-end/service/access-arrangements.service.spec.js
- admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
- admin/views/access-arrangements/select-access-arrangements.ejs
- test/admin-hpa/features/access_arrangements.feature
- test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
- test/admin-hpa/features/support/page_objects/select_access_arrangements_page.rb
Feature for school staff to provide a reason for the next question button.
> Feature/29465 NBQ reason

- admin/views/school/school-home.ejs
merging master into support branch for hotfix release
> Update trial support branch with HDF hotfix from master

- pupil-spa/src/app/services/question/warmup-question.service.ts
update practice questions to...
1. 1x12
2. 2x2
3. 10x10
> update practice questions

- functions/pupil-status/pupil-status-batch.service.js
- functions/readme.md
- add diagnostics output to pupil status function.  
- update readme
> bug/31018 - add diagnostics output to pupil status function

- admin/data/sql/migrations/20190325103327.do.add-job-id-pupil-upsert-proc.sql
- admin/data/sql/migrations/20190325103327.undo.add-job-id-pupil-upsert-proc.sql
- functions/census-import/census-import.data.service.js
- functions/census-import/job.data.service.js
- functions/census-import/v1.js
> Feature/31170 Include job id the pupil loading procedure

- admin/services/data-access/pupil-access-arrangements.data.service.js
Exclude pupils with previously submitted access arrangements from the ones in the select access arrangements list
> Bug/30818 Remove pupils with applied AAs from AA selection list

- admin/controllers/pupil.js
This will fix the issue where duplicate UPN is allowed within school while **editing** pupil
> Pass school id parameter when editing pupil

- test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
- test/admin-hpa/features/support/sql_db_helper.rb
Fixing issue with no active check window test
> feature/31684-nightly - Fix nightly build

- test/admin-hpa/Gemfile.lock
- test/admin-hpa/Rakefile
- test/admin-hpa/rerun.txt
> Feature/31837 - Nightly failures

- admin/data/sql/migrations/20190411172714.do.create-updatedat-column-triggers.sql
- admin/data/sql/migrations/20190411172714.undo.create-updatedat-column-triggers.sql
Added migration that creates triggers for updatedAt columns across all tables where this column name exists
> Feature/30621 updatedAt table triggers

- admin/data/sql/migrations/20190412151916.do.revoke-alter-and-delete-permissions-mtc-admin-user.js
- admin/data/sql/migrations/20190412151916.undo.revoke-alter-and-delete-permissions-mtc-admin-user.js
Reduce permission on mtc admin user since dedicated pupil census user is covering relevant tasks
> Feature/31715 Revoke specific mtc admin user permissions on pupil table

- admin/views/hdf/review-pupil-details.ejs
- If the pupil's first/last names and dob match another
> feature/29500 - Added pupil middlename to HDF review details page

- load-test/scenarios/restart-check/01-teacherLoginsForRestart.csv
- load-test/scenarios/restart-check/staff-restart-pupil-check-use-db.jmx
This branch have the below load test scenario, which will get the teacher names from the database and populates 01-teacherLoginsForRestart.csv before running the Restart-Check thread group.
staff-restart-pupil-check-use-db.jmx
> Added check restart load test scenario

- admin/data/sql/migrations/20190502111056.do.delete-tryitout-pins-view.sql
- admin/data/sql/migrations/20190502111056.undo.delete-tryitout-pins-view.sql
- admin/data/sql/migrations/20190502111953.do.create-new-tryitout-pin-view.sql
- admin/data/sql/migrations/20190502111953.undo.create-new-tryitout-pin-view.sql
- admin/services/data-access/pin-generation.data.service.js
- test/pupil-hpa/features/step_definitions/pupil_auth_steps.rb
'quick win' optimisations that were identified in Wednesdays session.
note: this _could_ have been done as a stored procedure, but the difference in filtering requirements between the 2 usages would have made this a lot more effort.  
More formal changes to this area of the system are planned, so this will do as an interim perf improvement
> Feature/32402 - optimise try it out pins view

- admin/services/data-access/pupil-register.data.service.js
- admin/services/pupil-register.service.js
- admin/spec/back-end/service/pupil-register.service.spec.js
Corrected query to fetch first record of a latest started but not received check
> Bug/32453 Incomplete status home page issue

- test/pupil-hpa/features/step_definitions/pupil_api.rb
So we can investigate why this only fails on the Test env and not locally
> remove assertion

- pupil-spa/src/app/header/header.component.ts
- pupil-spa/src/app/out-of-time/out-of-time.component.html
- pupil-spa/src/app/out-of-time/out-of-time.component.ts
UI changes and relocation of signOut and reset calls on afterViewInit event to properly address check type related behavior.
> Feature/32705 Out of time changes

- admin/views/partials/_cookie_message.ejs
Added missing element to allow cookie message banner hiding
> Bug/32391 Admin console error

- admin/data/sql/migrations/20190517101548.do.grant-unmask.js
- admin/data/sql/migrations/20190517101548.grant-unmask.js
- admin/data/sql/migrations/20190517104134.do.mask-psreport.sql
- admin/data/sql/migrations/20190517104134.undo.mask-psreport.sql
- admin/data/sql/migrations/20190517104628.do.mask-hdf.sql
- admin/data/sql/migrations/20190517104628.undo.mask-hdf.sql
- admin/data/sql/migrations/20190517104732.do.mask-user.sql
- admin/data/sql/migrations/20190517104732.undo.mask-user.sql
- admin/data/sql/migrations/20190517111616.do.mask-pupil.sql
- admin/data/sql/migrations/20190517111616.undo.mask-pupil.sql
- Creates dynamic masks for sensitive data columns in SQL Server.
- Grants unmasking permission to admin app role. 
- Creates migration for existing masks
> mask sensitive data columns and grant database user unmasking permission

- test/admin-hpa/features/generate_pupil_pins.feature
- test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
- test/admin-hpa/features/support/hooks.rb
- test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
- test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
- test/pupil-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
- test/pupil-hpa/features/support/page_objects/generate_pins_overview_page.rb
Adding some reliability after discovering an issue with the over night run
> adding various changes to tests

- test/admin-hpa/features/pupil_not_taking_check.feature
- test/admin-hpa/features/step_definitions/add_pupil_steps.rb
- test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
Resolve issues with the flakey sorting tests for the pupil not taking check tests
> 34971 - Resolve issue with sorting tests

- test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
- test/admin-hpa/features/support/hooks.rb
- test/pupil-hpa/features/support/sql_db_helper.rb
Some tests were resetting pins via SQL, we have removed this as it is not how it works in live
> Feature 35214 - refactored tests so we are not resetting pins

- test/admin-hpa/features/step_definitions/add_pupil_steps.rb
> remove commited binding.pry

- test/admin-hpa/features/step_definitions/add_pupil_steps.rb
- test/admin-hpa/features/support/page_objects/add_pupil_page.rb
- test/admin-hpa/features/support/page_objects/edit_pupil_page.rb
Tests have been run 50 times each to prove reliability
> 35931 - make upn tests more reliable

- deploy/storage/tables-queues.json
remove JSON comment as causing tools to fail.
> remove JSON comment

- admin/authentication/dfe-signin-strategy.js
- admin/services/dfe-signin.service.js
- admin/spec/back-end/service/dfe-signin.service.spec.js
> Bug/37911 - fix dfe sign in bugs

- test/admin-hpa/features/step_definitions/sign_in_steps.rb
- test/admin-hpa/features/support/page_objects/pupil_register_page.rb
Adding steps that were not committed.
> add missing selector and var

- admin/controllers/pupil-pin.js
- admin/data/sql/migrations/20191118121038.do.add-aliases-tryout-pin-generation-view.sql
- admin/data/sql/migrations/20191118121038.undo.add-aliases-tryout-pin-generation-view.sql
- admin/data/sql/migrations/20191118121046.do.add-aliases-live-pin-generation-view.sql
- admin/data/sql/migrations/20191118121046.undo.add-aliases-live-pin-generation-view.sql
- admin/data/sql/migrations/20191118161239.do.add-aliases-live-active-pin-view.sql
- admin/data/sql/migrations/20191118161239.undo.add-aliases-live-active-pin-view.sql
- admin/data/sql/migrations/20191118161247.do.add-aliases-tryout-active-pin-view.sql
- admin/data/sql/migrations/20191118161247.undo.add-aliases-tryout-active-pin-view.sql
- admin/helpers/pupil-name-presenter.js
- admin/services/check-start.service.js
- admin/services/data-access/check-form-allocation.data.service.js
- admin/spec/back-end/helpers/pupil-name-presenter.spec.js
- admin/views/partials/_print_pupils.ejs
- admin/views/pupil-register/_pupil-form.ejs
- functions/lib/prepared-check-schema-validator.js
- pupil-spa/src/app/login-success/login-success.component.html
- pupil-spa/src/app/login-success/login-success.component.spec.ts
- pupil-spa/src/app/login-success/login-success.component.ts
- pupil-spa/src/app/pupil.ts
Added new fields on prepare check config, relevant views and in display with priority on pupil spa
> Prioritise aliases on pupil spa welcome screen

- deploy/azure/service-bus/_run.sh
- deploy/azure/service-bus/template.json
remove zone redundancy setting as this is immutable in premium edition
> update service bus ARM template

- admin/config.js
- admin/services/check-start.service/check-start.service.js
- admin/services/prepare-check.service.js
- admin/services/prepared-check-sync.service.js
- admin/services/restart.service.js
- pupil-api/src/config.ts
- pupil-api/src/routes/auth.ts
- pupil-api/src/services/feature.service.ts
> align 2020 mode feature toggle for admin and auth API apps

- test/pupil-hpa/features/support/helpers.rb
> Add uuid and remove id

- load-test/scenarios/_2020/pin-gen/_jm5.live-pin-gen-with-check.jmx
- test/pupil-hpa/features/pin_expiry.feature
- test/pupil-hpa/features/step_definitions/pupil_api.rb
- test/pupil-hpa/features/support/sql_db_helper.rb
- tslib/src/functions/check-marker/check-form.service.ts
Fixes a bug caused by non-production ready code that improperly managed the sql connection pool.
> Bug/39235 - fix check form lookup in check marker function

- admin/controllers/helpdesk.js
remove double call to `next()`
> [admin] fix stacktrace appearing on helpdesk call

- _util/virtual-machines/.gitignore
- _util/virtual-machines/_common/minimize.sh
- _util/virtual-machines/_common/motd.sh
- _util/virtual-machines/_common/sshd.sh
- _util/virtual-machines/_common/virtualbox.sh
- _util/virtual-machines/mtc-test-vm/README.md
- _util/virtual-machines/mtc-test-vm/files/install_mtc.sh
- _util/virtual-machines/mtc-test-vm/http/preseed.cfg
- _util/virtual-machines/mtc-test-vm/scripts/cleanup.sh
- _util/virtual-machines/mtc-test-vm/scripts/docker-ce.sh
- _util/virtual-machines/mtc-test-vm/scripts/dotfiles.sh
- _util/virtual-machines/mtc-test-vm/scripts/dotnet.sh
- _util/virtual-machines/mtc-test-vm/scripts/install.sh
- _util/virtual-machines/mtc-test-vm/scripts/mtc.sh
- _util/virtual-machines/mtc-test-vm/scripts/networking.sh
- _util/virtual-machines/mtc-test-vm/scripts/nvm.sh
- _util/virtual-machines/mtc-test-vm/scripts/sudoers.sh
- _util/virtual-machines/mtc-test-vm/scripts/update.sh
- _util/virtual-machines/mtc-test-vm/scripts/zsh.sh
- _util/virtual-machines/mtc-test-vm/ubuntu-18.04-amd64.json
Packer template and scripts to create a VirtualBox machine with all dependencies installed
Useful for running e2e tests in the VM.
> Add support for building a VirtualBox testing image

- admin/services/data-access/config.data.service.js
- admin/services/data-access/retry-async.js
- admin/services/data-access/sql.service.js
- improve error info captured by retry handler in admin app
- switch config query from readonly to master
> add error info and remove readonly call

- admin/services/data-access/check-form-allocation.data.service.js
- admin/services/data-access/config.data.service.js
- admin/services/data-access/retry-async.js
- admin/services/data-access/sql.service.js
queries within pin gen sequence all target master, rather than read replica
> Feature/39453 switch select query to master during pin gen 

- admin/services/data-access/retry-async.js
- admin/services/data-access/sql.service.js
add additional predicate for sql retries on request timeouts
> add ETIMEOUT check

- func-consumption/package.json
Housekeeping
autobuild on `yarn:start` and deprecate yarn start:dev
> [func-consumption] - update package.json script tags

- pupil-spa/src/app/check/check.component.spec.ts
- pupil-spa/src/app/check/check.component.ts
Allow redirection on warmup complete check state
> Bug/39436 Edit your setting link on Practice completed check state not working

- admin/controllers/access-arrangements.js
- admin/controllers/pupil-register.js
- admin/spec/back-end/controllers/access-arrangements.spec.js
- admin/views/access-arrangements/overview.ejs
- admin/views/access-arrangements/unavailable-access-arrangements.ejs
- admin/views/availability/admin-window-unavailable.ejs
- admin/views/check-form/view-form.ejs
- admin/views/check-window/manage-check-windows.ejs
- admin/views/groups/groups.ejs
- admin/views/helpdesk/school-impersonation.ejs
- admin/views/pupil-register/pupils-list.ejs
- admin/views/pupils-not-taking-the-check/select-pupils.ejs
- admin/views/school/school-home.ejs
- admin/views/service-manager/sce-settings.ejs
- admin/views/service-manager/service-manager-home.ejs
- admin/views/test-developer/test-developer-home.ejs
- test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
- test/admin-hpa/features/support/page_objects/group_pupils_page.rb
- test/admin-hpa/features/support/page_objects/pupils_not_taking_check_page.rb
- test/pupil-hpa/features/support/page_objects/access_arrangements_page.rb
Availability feature updates and content changes across school home and overview feature pages
> Feature/39432 Data availability updates

- pupil-spa/src/app/check/check.component.spec.ts
- pupil-spa/src/app/check/check.component.ts
- pupil-spa/src/app/out-of-time/out-of-time.component.html
Allow preload view state to render timeout screen when next question AA is active for pupil
> Bug/39335 Allow preload view state for out of time page component render during check

- test/admin-hpa/Gemfile.lock
- test/pupil-hpa/Gemfile.lock
Upgrade rack to version 2.0.8 or later
Upgrade nokogiri to version 1.10.8 or later
> update nokogiri and rack versions

- admin/views/pupil-pin/view-and-custom-print-pins.ejs
> updated copy

- test/admin-hpa/features/generate_pupil_pins.feature
- test/admin-hpa/features/step_definitions/check_window_validation_steps.rb
- test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
> add audit tests and check window fix

- admin/services/data-access/headteacher-declaration.data.service.js
- test/admin-hpa/features/declaration_submitted.feature
- test/admin-hpa/features/step_definitions/assign_to_check_window_v2_steps.rb
- test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
- test/admin-hpa/features/support/hooks.rb
- test/admin-hpa/features/support/sql_db_helper.rb
Fixed both queries by identifying if the check is complete
> Bug/40163 HDF page inacessible

- pupil-spa/src/app/connectivity-check/connectivity-check.component.html
- pupil-spa/src/app/connectivity-check/connectivity-check.component.spec.ts
- pupil-spa/src/app/connectivity-check/connectivity-check.component.ts
- pupil-spa/src/app/login/login.component.html
- pupil-spa/src/app/login/login.component.spec.ts
- pupil-spa/src/app/login/login.component.ts
- pupil-spa/src/app/services/device/device.service.spec.ts
- pupil-spa/src/app/services/device/device.service.ts
Modified in both login and connectivity check component
> Feature/39479 Added detection for ie9/ie10 and flag as unsupported browsers

- functions-app/report-psychometrician-generate-staging-file/service/data.service.js
- tslib/src/functions/check-marker/check-marker.v1.ts
Store marking data with school UUID as the PK and `checkCode` as the RowKey
> 40692: refactor checkResult to include school UUID as PK

- _spikes-poc/batch-service/docker-worker/app/index.js
- admin/bin/gen-move-pupil-sql.js
- remove unnecessary async within foreach
- fix standard lint issue
> feature/34370 - small chores

- test/admin-hpa/features/support/env.rb
- test/pupil-hpa/features/support/env.rb
Added missing check for the .env file existence
> fix for pipeline issue

- admin/controllers/attendance.js
- admin/controllers/pupils-not-taking-the-check.js
- admin/services/data-access/pupil.data.service.js
- admin/services/pupil.service.js
- admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
- admin/spec/back-end/service/pupil.service.spec.js
- refactor use of data service to service
> feature/17262 Attendance Controller Dependency Fix

- test/admin-hpa/features/support/env.rb
- test/pupil-hpa/features/support/env.rb
This needs to be removed so that on the pipeline, it can automatically choose the correct chrome driver version
> remove required chrome version

- api_tests/Gemfile
- api_tests/Gemfile.lock
- api_tests/README.md
- test/admin-hpa/Dockerfile
- test/admin-hpa/Gemfile
- test/admin-hpa/Gemfile.lock
- test/admin-hpa/README.md
- test/pupil-hpa/Dockerfile
- test/pupil-hpa/Gemfile
- test/pupil-hpa/README.md
> update required ruby version

- test/admin-hpa/Gemfile.lock
- test/pupil-hpa/Gemfile.lock
Committing changes to Gemfile.lock
> commit changes to gemfile.lock

- test/admin-hpa/config/browserstack.yml
- test/pupil-hpa/config/browserstack.yml
> edge config

- test/admin-hpa/Gemfile
- test/admin-hpa/Gemfile.lock
- test/admin-hpa/features/support/env.rb
- test/pupil-hpa/Gemfile
- test/pupil-hpa/Gemfile.lock
> updating rack to 2.2.3

- test/admin-hpa/features/retro_input_assistance.feature
- test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
- test/admin-hpa/features/step_definitions/retro_input_steps.rb
- test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
- test/admin-hpa/features/support/page_objects/retro_input_page.rb
- test/admin-hpa/features/support/page_objects/select_access_arrangements_page.rb
- test/pupil-hpa/features/step_definitions/retro_input_steps.rb
- test/pupil-hpa/features/support/page_objects/access_arrangements_page.rb
- test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
Commit was missed as part of https://github.com/DFEAGILEDEVOPS/MTC/pull/1699.
This is what was intended to be committed as part of that PR
> add missing retro tests

- test/admin-hpa/features/step_definitions/groups_steps.rb
Add a new pupil to ensure reliability and control of the test data
> fix broken group test

- admin/spec/back-end/lib/validator/pupil-validator.spec.js
- test/admin-hpa/features/step_definitions/add_pupil_steps.rb
- tslib/src/config.ts
Add sql option `enableArithAbort`, default to true.
> [tslib] support sql option `enableArithAbort`

- test/admin-hpa/features/school_import.feature
- test/admin-hpa/features/support/hooks.rb
- test/admin-hpa/features/upload_pupil_census.feature
> feature/44207 - fix pipeline fails

- test/admin-hpa/Rakefile
- test/pupil-hpa/Rakefile
> remove references

- db/config.js
- db/engine/createDatabase.js
Fix for Azure migrations validation
> Increase request timeout when asking Azure to create a database

- func-consumption/util-school-pin-http-service/function.json
- tslib/src/config.ts
- tslib/src/functions/util-school-pin-http-service/index.ts
- tslib/src/functions/util-school-pin-sampler/index.ts
- tslib/src/functions/util-submit-check/index.ts
- prefix school pin http sampler with 'util'
- consolidate util enabled flag into one setting
> feature/44806 - rename function, consolidate util flag into one setting

- .gitignore
- test/admin-hpa/features/data_sync.feature
- test/pupil-hpa/features/pupil_data_sync.feature
- test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
- test/pupil-hpa/features/support/sql_db_helper.rb
Scenario Outline: Answers events and inputs all match up
Given I have completed the check with only <correct_answers> correct answers
When the data sync function has run
Then all answers events and inputs match
Examples:
| correct_answers |
| 0               |
| 1               |
| 3               |
| 5               |
| 8               |
| 13              |
| 21              |
| 25              |
> feature/45115 - Data team scenarios

- test/pupil-hpa/features/pupil_data_sync.feature
- test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
Following the meeting with the data team, they want a testing scenario that captures all possible keyboard inputs. 
The scenario is as follows
Scenario: All keyboard keys are recorded as inputs
Given I have completed a check by selecting all keys on the keyboard
When the data sync function has run
Then I should see all inputs recorded
> Feature/45159 - Data Team - Inputs scenario

- admin/lib/validator/common/date-validator.js
- admin/spec/back-end/lib/validator/common/date-validator.spec.js
Fix an error inadvertently introduced by the recent linter upgrade when resolving lint issues
> Fix date validator

- admin/controllers/access-arrangements.js
- admin/services/pupil-access-arrangements.service.js
- admin/spec/back-end/controllers/access-arrangements.spec.js
- admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
> bug/45474 deleting access arrangement with invalid UUID crashes node

- test/admin-hpa/features/view_custom_pins_familiarisation.feature
- test/pupil-hpa/features/step_definitions/ps_report_steps.rb
wip'd a test for future investigation and increased wait time
> fix issue with tests

- docs/psychometric-report-scaling.md
add notes on ps report testing concurrency improvements
> chore - add ps report scaling notes

- admin/views/accessibility-statement.ejs
- pupil-spa/src/app/accessibility-statement/accessibility-statement.component.html
> [admin, spa] copy change

- test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
- test/admin-hpa/features/generate_pupil_pins.feature
Added test to check only 1 TIO pin per pupil is allowed
> feature/46558 - TIO pin test

- test/admin-hpa/features/service_bus_queue_config.feature
Skipping service bus config tests
> skipping service bus tests until ready

- test/admin-hpa/features/add_multiple_pupil.feature
- test/admin-hpa/features/assign_to_check_window_v2.feature
- test/admin-hpa/features/groups.feature
- test/admin-hpa/features/mod_schools.feature
- test/admin-hpa/features/results.feature
- test/admin-hpa/features/school_landing.feature
- test/admin-hpa/features/step_definitions/assign_to_check_window_v2_steps.rb
- test/admin-hpa/features/step_definitions/result_page_steps.rb
- test/admin-hpa/features/support/helpers.rb
- test/admin-hpa/features/view_custom_pins_familiarisation.feature
- test/pupil-hpa/features/event_auditing.feature
- test/pupil-hpa/features/feedback.feature
- test/pupil-hpa/features/header_footer.feature
- test/pupil-hpa/features/loading_page.feature
- test/pupil-hpa/features/pin_expiry.feature
- test/pupil-hpa/features/registered_inputs.feature
- test/pupil-hpa/features/step_definitions/registered_inputs_steps.rb
- test/pupil-hpa/features/support/page_objects/check_page.rb
- test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
Alot of tests were set to @wip, the majority are now reinstated
> Reinstating work in progress tests

- db/migrations/schema-objects/20210621004933.do.alter-table-user-device-remove-tinyint.sql
- db/migrations/schema-objects/20210621004933.undo.alter-table-user-device-remove-tinyint.sql
- tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
> 47286 - Sync results to sql - rollback issue

- admin/views/availability/admin-window-unavailable.ejs
Update service unavailable message
> [admin] update service unavailable message

- admin/package.json
- admin/yarn.lock
- func-consumption/package.json
- func-consumption/yarn.lock
- func-throttled/package.json
- func-throttled/yarn.lock
- functions-app/yarn.lock
- load-test/package.json
- pupil-api/package.json
- pupil-api/yarn.lock
- pupil-spa/yarn.lock
- tslib/package.json
- tslib/yarn.lock
Consolidated security updates for path-parse and ioredis
> Security updates: path-parse, ioredis

- test/admin-hpa/config/cucumber.yml
- test/admin-hpa/features/service_manager_message.feature
- test/admin-hpa/features/step_definitions/service_message.rb
- test/admin-hpa/features/support/page_objects/create_message_page.rb
- test/admin-hpa/features/support/page_objects/school_landing_page.rb
- test/pupil-hpa/config/cucumber.yml
Add missing tests for service message
> add tests for service message

- test/admin-hpa/Rakefile
- test/admin-hpa/config/cucumber.yml
- test/pupil-hpa/Rakefile
- test/pupil-hpa/config/cucumber.yml
Fix issue with rerun not knowing which tags to run
Weekend profile to only run the @weekend tag
> Fix weekend run

- admin/package.json
- admin/yarn.lock
- func-consumption/package.json
- func-consumption/yarn.lock
- func-throttled/package.json
- func-throttled/yarn.lock
- load-test/package.json
- pupil-api/package.json
- pupil-api/yarn.lock
- tslib/package.json
- tslib/yarn.lock
Security fix - update ramda to 0.27.2
> Feature/security rollup ramda 0.27.2

- test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
- test/admin-hpa/features/step_definitions/csrf_steps.rb
- test/admin-hpa/features/step_definitions/custom_pins_familiarisation_steps.rb
- test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
- test/admin-hpa/features/step_definitions/generate_pupil_pin_familiarisation_steps.rb
- test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
- test/admin-hpa/features/step_definitions/helpdesk_pin_steps.rb
- test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
- test/admin-hpa/features/step_definitions/pupil_status_steps.rb
- test/admin-hpa/features/step_definitions/restarts_steps.rb
- test/admin-hpa/features/step_definitions/view_and_custom_print_for_live_check_steps.rb
- test/admin-hpa/features/support/helpers.rb
- test/admin-hpa/features/support/page_objects/generate_live_pins_overview_page.rb
- test/admin-hpa/features/support/page_objects/generate_tio_pins_overview_page.rb
- test/admin-hpa/features/support/page_objects/view_and_print_live_pins_page.rb
- test/admin-hpa/features/support/page_objects/view_and_print_tio_pins_page.rb
Updated names of page objects along with var names to be more in line with current functionality
> update page objects

- admin/views/hdf/declaration-form.ejs
- admin/views/partials/_attendance_code_reasons.ejs
- admin/views/pupil-pin/select-official-or-try-it-out-pins.ejs
- admin/views/pupil-pin/view-and-custom-print-pins.ejs
- admin/views/pupil-register/_pupil-form.ejs
- admin/views/pupil-status/view-pupil-status.ejs
- admin/views/restart/restart-overview.ejs
- test/admin-hpa/features/step_definitions/pupil_status_steps.rb
- test/admin-hpa/features/support/page_objects/view_and_print_live_pins_page.rb
- test/admin-hpa/features/support/page_objects/view_and_print_tio_pins_page.rb
further edits to content changes.
> feature/51753 content changes pt.2

- admin/services/restart-v2.service.js
- admin/spec/back-end/service/restart-v2.service.spec.js
Wording change for the teacher when a discretionary restart has been applied.
> 51816 restart wording change

- test/pupil-hpa/features/check.feature
- test/pupil-hpa/features/support/hooks.rb
> add hooks to tests which are to assert for check started timestamp

- db/seeds/20181116123710.custom.devtest-pupil-school.sql
- switch Dfe Number to one that is in use
> bug/56860 - fix data seeding SQL script issue

- deploy/build-defs/validate-pr-db-migrations.yml
- switch to gen 5 database for PR validation
> bug/58963 - Gen 4 SQL Azure Retired.  Switch to Gen 5 for PR validation

- admin/controllers/pupils-not-taking-the-check.js
- admin/services/data-access/attendance-code.data.service.js
- admin/services/data-access/pupil-attendance.data.service.js
- db/migrations/core-data/20230427142256.do.attendance-code-hide-absent.sql
- db/migrations/core-data/20230427142256.undo.attendance-code-hide-absent.sql
- db/migrations/schema-objects/20230427134557.do.attendance-code-visible-column.sql
- db/migrations/schema-objects/20230427134557.undo.attendance-code-visible-column.sql
- test/admin-hpa/features/pupil_audit.feature
- test/admin-hpa/features/pupil_not_taking_check.feature
- test/admin-hpa/features/pupil_status.feature
- test/admin-hpa/features/service_manager_pupil_search.feature
- test/admin-hpa/features/step_definitions/declaration_review_pupil_steps.rb
- test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
- test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
- test/admin-hpa/features/support/page_objects/pupil_reason_page.rb
- test/admin-hpa/features/support/sql_db_helper.rb
- create flag to preserve visibility of attendance code
- disable selection if not visible
- hide `ABSNT` attendance code
> feature/58889 - Hide attendance codes

- admin/views/cookies-form.ejs
- api_tests/Gemfile.lock
- api_tests/spec/security_spec.rb
- test/admin-hpa/features/breadcrumbs.feature
- test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
- test/admin-hpa/features/step_definitions/result_page_steps.rb
- test/pupil-hpa/features/a_ps_report.feature
Add breadcrumbs to cookie page
> [58709] bug/58709-admin-cookies-breadcrumbs

- README.md
- grant permissions on repository for codacy gated checks
- fix codacy badge markdown on root readme file
> bug/56112 Fix Codacy Badge on Root Readme

- .circleci/config.yml
fix issue where chromedriver can no longer be sourced
> bug/60482 Circle CI chromedriver failed install

- pupil-api/vso-add-build-and-commit.sh
- tslib/src/pupil-api/services/ping.service.ts
relocate auth api build meta to `dist` folder
> 62798 Part 2. relocate meta files to dist folder

- test/admin-hpa/features/step_definitions/pupil_register_steps.rb
- test/admin-hpa/features/step_definitions/pupil_status_steps.rb
Removing zero padding from dates from pupil register tests
> remove zero padding from dates

- test/admin-hpa/features/support/env.rb
- test/se_manager/.cache/selenium/se-metadata.json
Printing redis connection details
> redis connection details

- db/migrations/schema-objects/20240529151328.do.pupil-audit-new-data-mask.sql
- db/migrations/schema-objects/20240529151328.undo.pupil-audit-new-data-mask.sql
add data mask to the newData column in pupilAudit table
> bug/64757 mask newData field in pupilAudit table

- admin/views/hdf/declaration-form.ejs
reflect the fact that it does not have to be the headteacher making the submission
> feature/64782 HDF Text instruction update

- admin/controllers/tech-support.js
- admin/package.json
- admin/routes/tech-support.js
- admin/services/data-access/service-bus-queue-admin.data.service.js
- admin/services/queue-management.service.js
- admin/spec/back-end/controllers/tech-support.spec.js
- admin/spec/back-end/service/queue-management.service.spec.js
- admin/views/tech-support/home.ejs
- admin/views/tech-support/ps-report-run.ejs
- admin/views/tech-support/queue-overview.ejs
- admin/views/tech-support/sb-queue-submit.ejs
add functionality to send ad-hoc service bus messages manually
> bug/64795 Tech support - send service bus messages

- func-ps-report/host.json
Ps report lock renewal update
Align maxAutoRenewDuration with functionTimeout
> Increase maxAutoRenewDuration to align with functionTimeout

- admin/package.json
- admin/views/availability/admin-window-unavailable.ejs
- test/admin-hpa/features/step_definitions/post_check_window_steps.rb
Update copy when site unavailable rather than read-only
> 65515-copy-change

- test/admin-hpa/features/step_definitions/result_page_steps.rb
- test/se_manager/.cache/selenium/se-metadata.json
update filename for ctf from KS2 to MTC
> Fix filename for CTF

- test/admin-hpa/features/step_definitions/result_page_steps.rb
> Remove binding.pry

- .gitignore
- test/admin-hpa/features/step_definitions/add_multiple_pupil_steps.rb
- test/admin-hpa/features/support/hooks.rb
- test/admin-hpa/features/support/request_helper.rb
- test/se_manager/.cache/selenium/se-config.toml
- test/se_manager/.cache/selenium/se-metadata.json
Test fixes for the pipeline failures
> test fixes

- test/admin-hpa/Rakefile
- test/admin-hpa/features/step_definitions/edit_check_window_steps.rb
- test/pupil-hpa/Rakefile
- test/pupil-hpa/tags-parallel.txt
Fix for check window end date error 10 years in future
> Check window error test fix

- test/pupil-hpa/features/step_definitions/pupil_api.rb
- test/se_manager/.cache/selenium/se-metadata.json
Updated pupil feedback url in test
> expected url change

- admin/views/dfe-sign-in-error-missing-org.ejs
- admin/views/dfe-sign-in-error.ejs
- pupil-spa/src/app/login-failure/login-failure.component.html
Updating error messages displayed to applicant
> Updating error page contact details
